### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kittyBS** [GReD-Clermont/sRNAPipe#10]
Hello!
I'm having trouble installing the tool. First of all, I can find the tool on the "Galaxy Tool Shed", but I cannot find it on the "https://usegalaxy.org/" site. As you stated on the closed "executable? #7" issues, I also tried to install it with "conda install bioconda::srnapipe" and "git clone https://github.com/GReD-Clermont/sRNAPipe-cli.git", but both options failed to install the packages. I could not install the tool due to incompatibilities between them (Although I created env with different Python versions, packages/tools that are incompatible with each other are created every time). Can you guide me to use the tool?

**Comment by ppouchin** [comment]
Hello!

If you find it on the Galaxy Tool Shed, you should be able to install it on your own Galaxy instance. 
The *usegalaxy.org* maintainers have not installed this tool on the public instance, thus why it is not available there.
I think you can find it on https://usegalaxy.eu though.

> I also tried to install it with "conda install bioconda::srnapipe" and "git clone https://github.com/GReD-Clermont/sRNAPipe-cli.git", but both options failed to install the packages. I could not install the tool due to incompatibilities between them (Although I created env with different Python versions, packages/tools that are incompatible with each other are created every time). Can you guide me to use the tool?

`conda install bioconda::srnapipe` should install what you find on https://github.com/GReD-Clermont/sRNAPipe-cli to your conda env. You don't need any `git clone`. If you want to use it on the command line, you just create a conda environment with srnapipe, and then you use it by typing `srnapipe`:

```bash
conda create -n myenv bioconda::srnapipe
conda activate myenv
srnapipe
```

However, the easiest way is to install it on a Galaxy instance or on usegalaxy.eu.

**Comment by kittyBS** [comment]
Thank you for giving such a clear answer in such a short time.
