### ISSUE TITLE
Some comments on the Galaxy wrapper

### ISSUE THREAD

**Issue by bebatut** [GReD-Clermont/sRNAPipe#2]
- General comments:
  - Identation: 4 spaces
  - Missing `version_command` element ([doc](https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-version-command)) before `command`
- Toolshed yaml file ([doc](https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/shed_yml.html))
  - Missing parameters: `homepage_url`, `long_description`, `remote_repository_url`, `type`
  - Order of parameters: `name`, `owner`, `description`, `homepage_url`, `long_description`, `remote_repository_url`, `type`, `categories`
- Command section
  - Add `detect_errors="aggressive"` to get `<command detect_errors="aggressive">` ([doc]( https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html#exit-code-detection))
  - Indentation and mainly PEP8 conformant
  - Use only `'` around every parameter name (except boolean)
- Input section
  - Use `argument` attribute to include the long form of the underlying tool parameter (will be automatically displayed inside the parameter help). It could also be used to replace the `name` attribute ([doc](https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html#parameter-name-argument-and-help))
  - Order of parameter attributes: `name`, `argument`, `type`, `format`, `label`, `help` ([doc](https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html#coding-style))
  - Use of macros and [sections](https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-section) for more user-friendliness and less redundancy
   
    Because for each conditional you have the same param to choose from history or build-in, you could create macros for that and limit the redundancy but also section to help user to navigate through it. Something like:

    - Adding after `description`:

     ```
     <macros>
         <xml name="source">
             <conditional name="source">
                 <param name="source" type="select" label="Will you select the database from your history or use a built-in index?">
                     <option value="indexed">Use a built-in index</option>
                     <option value="history">Use one from the history</option>
                 </param>
                 <when value="indexed">
                     <param name="indices" type="select" label="Select a reference genome">
                         <options from_data_table="bwa_indexes">
                             <filter type="sort_by" column="2" />
                             <validator type="no_options" message="No indexes are available" />
                         </options>
                     </param>
                 </when>
                 <when value="history">
                     <param name="file" type="data" format="fasta" label="Select a reference from history" />
                 </when>
             </conditional>
         </xml>
     </macros>
     ```

    - Replace with `<param name="*Source"` by `<expand macro="source"/>` in `input`:

     ```
     <section name="genome" title="Reference genome" expanded="true">
         <expand macro="source"/>
     </section>
     ```

    - Replace in `command` the parameter name with sth like:

     ```
     #if $genome.source.source == "history"
         --ref '${genome.source.file}'
         --build_index
     #else
        --ref '${genome.source.indices.fields.path}'
     #end if
     ```

    - Use section and conditional in `tests` with sth like:

     ```
     <section name="genome">
         <conditional name="source">
             <param name="source" value="history"/>
             <param name="file" value="genome-small.fa"/>
         </conditional>
     </section>
     ```

- Output section
  - Use label maybe more informative, sth like `"${tool.name} on ${first_input.name} (${on_string}): HTML report"`

I know it is a lot of comments (sorry), but take whatever you think it is useful for you 😄  and let me know if you need any help or if my comments are not clear!

---
Some useful links:
- Galaxy Tool XML File: https://docs.galaxyproject.org/en/latest/dev/schema.html
- Galaxy IUC best practices: https://galaxy-iuc-standards.readthedocs.io/en/latest/
- Galaxy IUC reviewer guide: https://github.com/galaxyproject/tools-iuc/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by ppouchin** [comment]
I removed "perl" and "r-base" from the dependencies, making them implicit, but it drastically reduced the time required to create the conda environment. And now, Travis successfully runs tests on the repo.

**Comment by bebatut** [comment]
great news!

**Comment by ppouchin** [comment]
Thank you for your help!
