### ISSUE TITLE
Cannot view all HTML components in sRNAPipe output

### ISSUE THREAD

**Issue by lhkelley** [GReD-Clermont/sRNAPipe#5]
I am using sRNAPipe to look at some small RNA-seq data. When I get to the html output I can’t view all of the images or parts of the images are missing. I think this has something to do with the whitelist. I enabled sRNAPipe, but I am still not getting a complete html. How do I know what other programs to enable with whitelist? Or is something else the problem?

The Galaxy community responded with:

"This looks like a dependency issue, not a whitelist issue.

If you are sure that all of the “Prerequisites” they list out are correct, or if you not sure/have questions about them, contact the tool wrapper author at their Github repository (open an issue). They are the best people to help troubleshoot what is going wrong. The repository was last updated in Feb 2019 – and Galaxy itself has had a few revisions since then. The tool installation might not work as intended anymore."

Do you have any idea what's going on with this issue?

Thank-you!

**Comment by ppouchin** [comment]
Hi, 

Unfortunately, I currently have no idea of what's happening. Which version of Galaxy are you using?
I'll try to set up a new instance to try it myself using the same version as you to check if something is missing.
However, I won't be able to do so until the start of december.

**Comment by ppouchin** [comment]
It seems the "pie_chart.png" which is generated through R is missing the text for some reason. The dependencies should be met though, so I will need to investigate further.
It does work on our server, but not on new instances, even just using the CLI version with miniconda. So something may indeed be missing.

**Comment by ppouchin** [comment]
Ok, so it seems I don't have this problem on Ubuntu/Debian when the package "fonts-liberation" is installed. 
I'll have to see if I can update the conda-recipe to include fonts for R, but in the meantime, you should be able to fix this by installing the corresponding fonts at the OS level, if you can.
For example, on Ubuntu/Debian, this should solve the problem:
`sudo apt install fonts-liberation`

**Comment by ppouchin** [comment]
If accepted, [this PR](https://github.com/bioconda/bioconda-recipes/pull/19052) should fix the issue.

**Comment by ppouchin** [comment]
[This](https://github.com/bioconda/bioconda-recipes/pull/19170) should have solved the issue.
@lhkelley Could you try to reinstall sRNAPipe to check if it works for you?
