### ISSUE TITLE
Can not download files from smallRNA pipe

### ISSUE THREAD

**Issue by Toluwalase2020** [GReD-Clermont/sRNAPipe#6]
Good day, I used the smallRNA pipe to analyse my data (41 samples) and I got a html report, however I have been unable to download any of the count table which i need for downstream analysis. I am assuming that The count data from the transcripts is the file to use. Am I right?

Also, I am confused as to which of the files to carry on to downstream analysis with DESEQ to understand the differential expression or is this not possible?

Is it possible to merge the individual data statistics of the samples similar to what multiqc does?

Thanks.

**Comment by ppouchin** [comment]
How have you been unable to download any of the count table?
As explained in the manual, you should be able to do so by clicking "View details" and choosing the data you want from there.
Also, as a last resort, you can always download the whole dataset from Galaxy.

Other than that, I wouldn't know which file you need to use for your analysis though.
Although for DESEQ, from what I've been told, as long as you have a tabular file with "counts", you should be able to use it.
