### ISSUE TITLE
executable?

### ISSUE THREAD

**Issue by OwenWato** [GReD-Clermont/sRNAPipe#7]
Newbie here but shouldnt there be a downloadable executable file such as srnapipe.pl , in conjunction with the .xml definition file? When I try to run with just the definition file I get error:  tool_script.sh line 9: snrapipe:command not found. 

Cheers

**Comment by ppouchin** [comment]
Following recommendations from Galaxy developers, the package was split in 2, with the Galaxy wrapper in this repo and the tool itself in that one : https://github.com/GReD-Clermont/sRNAPipe-cli

However, to use sRNAPipe from the command line, you can just use [bioconda to install it](https://anaconda.org/bioconda/srnapipe) (that's what Galaxy does when you install sRNAPipe from the toolshed). 

Does that answer your question?

**Comment by OwenWato** [comment]
Hi yes thanks for clarifying, however still running into issues. When I dragged the tool to same path as the wrapper, I still received the same error on the web server. I then installed the CL version and used the trial data provided- receiving another error: 
$ srnapipe --fastq test-data/reads-sample-small.fastq --fastq_n sample --ref test-data/genome-small.fa [--build_index] --transcripts test-data/transcripts-file-small.fa [--build_transcripts] --TE test-data/TE-file-smal
l [--build_TE] --miRNAs test-data/mirbase-21-dme-hairpins-16jul2015.fa [--build_miRNAs] --snRNAs test-data/dmel-all-sn-snoRNA-r6.03.fasta [--build_snRNAs] --rRNAs test-data/dmel-all-rRNA-r6.03.fasta [--build_rRNAs] --tRNAs test-data/dmel-all-tRNA-r6.03.fasta [--buid_tRNAs] --dir test-results --html results.html
Invalid version format (non-numeric data) at /home/owen/miniconda3/lib/site_perl/5.26.2/Statistics/R.pm line 369.
Something went wrong!

**Comment by ppouchin** [comment]
You should not put square brackets ("[" and "]") on the command line. These are used to indicate that this is an optional parameter (e.g. you use the "--build_X" when you provide a FASTA file, but you don't use it when you provide a BWA index). 

I don't know if it will solve this error though.

**Comment by OwenWato** [comment]
Hi thanks for that, I reran but received the same bug. I am using the sample files provided with a perl V>5.1 with Statistics::R installed so cannot explain this error.

$ srnapipe --fastq reads-sample.fastq --fastq_n sample --ref genome-small.fa --build_index --transcripts transcripts-file-small.fa --build_transcripts --TE TE-file-small --build_TE --miRNAs mirbase-21-dme-hairpins-16jul2015.fa --build_miRNAs --snRNAs dmel-all-sn-snoRNA-r6.03.fasta --build_snRNAs --rRNAs dmel-all-rRNA-r6.03.fasta --build_rRNAs --tRNAs dmel-all-tRNA-r6.03.fasta --build_tRNAs --dir test-results --html results.html
Invalid version format (non-numeric data) at /home/owen/miniconda3/lib/site_perl/5.26.2/Statistics/R.pm line 369.
Something went wrong!

**Comment by ppouchin** [comment]
Could you try installing it from bioconda maybe?

**Comment by OwenWato** [comment]
When I install from conda there is no fastq sample in the fastq_dir or test-results dir, I copied it from the manual install but received the same error.

**Comment by ppouchin** [comment]
Ok. You actually need to specify the complete path to the files, as these will be symlinked in the working directory.
Putting the "test-data" folder under in /tmp, the following command works for me:

```
srnapipe --fastq '/tmp/test-data/reads-sample.fastq' --fastq_n 'reads-sample-small.fastq' --min 18 --max 29  --ref '/tmp/test-data/genome-small.fa' --build_index --mis 0  --transcripts '/tmp/test-data/transcripts-file-small.fa' --build_transcripts  --TE '/tmp/test-data/TE-file-small.fa' --build_TE --misTE 3  --miRNAs '/tmp/test-data/mirbase-21-dme-hairpins-16jul2015.fa' --build_miRNAs  --snRNAs '/tmp/test-data/dmel-all-sn-snoRNA-r6.03.fasta' --build_snRNAs  --rRNAs '/tmp/test-data/dmel-all-rRNA-r6.03.fasta' --build_rRNAs  --tRNAs '/tmp/test-data/dmel-all-tRNA-r6.03.fasta' --build_tRNAs  --si_min 21 --si_max 21 --pi_min 23 --pi_max 29 --dir results --html results.html --PPPon true --threads 4
```

**Comment by ppouchin** [comment]
Is it solved?
